evaluation:
  tool: metaquast
  corrected_fasta: /home/yczhang/zyc/final_result/mhc/nano/lordec1.fa
run: {id: mhc_ont_50x_lordec_original, coverage: 50x, method: lordec, parameter_set: original}
lordec_k: 31
lordec_solid: 5
