evaluation:
  tool: quast
  corrected_fasta: /home/yczhang/zyc/final_result/Arabidopsis/data/sim/cor/ratatosk1.fa
run: {id: arabidopsis_sim_32x_ratatosk_original, coverage: 32x, method: ratatosk, parameter_set: original}
ratatosk_k1: 31
ratatosk_k2: 63
