evaluation:
  tool: metaquast
  corrected_fasta: /home/yczhang/zyc/final_result/100strains/100_cor/F_HERO.fa
run: {id: 100strains_legacy_30x_f_hero_original, coverage: 30x, method: f_hero, parameter_set: original}
fmlrc_k1: 21
fmlrc_k2: 59
hero_split: 10
hero_iterations: 1
