evaluation: {tool: quast}
run: {id: arabidopsis_10x_dadec, coverage: 10x, method: dadec, parameter_set: original}
parameter_profile: study
dadec_k1: 39
dadec_k2: 39
dadec_split: 1
dadec_threshold: 0.1
dadec_abundance1: 2
dadec_abundance2: 1