dataset:
  id: 100strains_legacy
  variant: current
  expected_genomes: 100
  long_coverage: 10x

evaluation:
  tool: metaquast

inputs:
  long_reads: /home/yczhang/zyc/final_result/100strains/data/long/long_reads.fa
  short_reads:
    30x: /home/yczhang/zyc/final_result/100strains/data/short/short_reads.fa
  genome_map: /home/yczhang/zyc/final_result/100strains/data/CAMI_paths.tsv
  simulation_configs: []
