# benchmark/config/datasets/mhc.yaml
dataset:
  id: mhc_ont
  variant: current
  expected_genomes: 1
  long_coverage: 10x

evaluation:
  tool: metaquast

inputs:
  long_reads: /home/yczhang/zyc/final_result/mhc/data/nano/reads.fa
  short_reads:
    50x: /home/yczhang/zyc/final_result/mhc/data/illumina/short-reads.fa
  genome_map: benchmark/config/datasets/mhc_genome_to_id.tsv
  simulation_configs: []

