evaluation:
  tool: quast
  corrected_fasta: /home/yczhang/zyc/final_result/Arabidopsis/data/sim/cor/F_HERO.fa
run: {id: arabidopsis_sim_32x_f_hero_original, coverage: 32x, method: f_hero, parameter_set: original}
fmlrc_k1: 21
fmlrc_k2: 59
hero_split: 2
hero_iterations: 1
