evaluation:
  tool: quast
  corrected_fasta: /home/yczhang/zyc/final_result/Arabidopsis/data/sim/cor/L_HERO.fa
run: {id: arabidopsis_sim_32x_l_hero_original, coverage: 32x, method: l_hero, parameter_set: original}
lordec_k: 31
lordec_solid: 5
hero_split: 2
hero_iterations: 1
