dataset:
  id: ecoli3_error_readcount
  variant: readcount
  expected_genomes: 3
  long_coverage: 20x

evaluation:
  tool: metaquast

inputs:
  long_reads: /home/work/wenhai/dadec/data/errors_ecoli3_readcount/long/sim_ecoli3_long_error_20x.fastq
  short_reads:
    20x: /home/work/wenhai/dadec/data/errors_ecoli3_readcount/miseq/miseq_reads.fastq.gz
    21x: /home/work/wenhai/dadec/data/errors_ecoli3_readcount/nextseq/nextseq_reads.fastq.gz
    22x: /home/work/wenhai/dadec/data/errors_ecoli3_readcount/novaseq/novaseq_reads.fastq.gz
    23x: /home/work/wenhai/dadec/data/errors_ecoli3_readcount/hiseq/hiseq_reads.fastq.gz
  genome_map: benchmark/config/datasets/ecoli3_genome_to_id.tsv
  simulation_configs:
    - data/errors_ecoli3_readcount/simulation_manifest.tsv
    - data/errors_ecoli3_readcount/miseq/miseq_readcount_30x.summary.tsv
    - data/errors_ecoli3_readcount/nextseq/nextseq_readcount_30x.summary.tsv
    - data/errors_ecoli3_readcount/novaseq/novaseq_readcount_30x.summary.tsv
    - data/errors_ecoli3_readcount/hiseq/hiseq_readcount_30x.summary.tsv
    - data/errors_ecoli3_readcount/long/sim_ecoli3_long_error_20x.manifest.tsv
