evaluation: {tool: quast}
run: {id: ecoli_error_hiseq_dadec_original, coverage: 23x, method: dadec, parameter_set: original}
dadec_k1: 31
dadec_k2: 31
dadec_split: 1
dadec_threshold: 0.08
dadec_abundance1: 2
dadec_abundance2: 1
